source 'https://supermarket.chef.io'

cookbook 'windows', '= 1.44.3'
cookbook 'apt', '= 3.0.0'
cookbook 'build-essential', '= 3.2.0'
cookbook 'newrelic', '= 2.0.0'
cookbook 'yum', '= 3.13.0'
cookbook 'yum-epel', '= 0.7.1'
cookbook 'chef_handler', '= 1.4.0'
cookbook 'curl', '= 2.0.2'
